def garden_operations(error_type: str) -> None:
    """Causes different errors depending on the parameter."""
    if error_type == "value":
        int("abc")
    elif error_type == "zero":
        1 / 0
    elif error_type == "file":
        open("missing.txt", "r")
    elif error_type == "key":
        my_garden = {"rose": 10, "oak": 5}
        my_garden["missing_plant"]


def test_error_types() -> None:
    """Test and capture the different errors generated by garden_operations."""
    print("=== Garden Error Types Demo ===\n")
    print("Testing ValueError...")
    try:
        garden_operations("value")
    except ValueError as e:
        print(f"Caught ValueError: {e}\n")

    print("Testing ZeroDivisionError...")
    try:
        garden_operations("zero")
    except ZeroDivisionError as e:
        print(f"Caught ZeroDivisionError: {e}\n")

    print("Testing FileNotFoundError...")
    try:
        garden_operations("file")
    except FileNotFoundError:
        print("Caught FileNotFoundError: No such file 'missing.txt'\n")

    print("Testing KeyError...")
    try:
        garden_operations("key")
    except KeyError as e:
        print(f"Caught KeyError: {e}\n")

    print("Testing multiple errors together...")
    try:
        garden_operations("zero")
    except (ValueError, ZeroDivisionError, FileNotFoundError, KeyError):
        print("Caught an error, but program continues!\n")

    print("All error types tested successfully!")


if __name__ == "__main__":
    test_error_types()
